SUPABASE_URL = "https://alliance-dice-new.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzb25kZnlhamNsdG5qem1tYW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNjUyNDEsImV4cCI6MjA5MzY0MTI0MX0.qB0qbP1KESivFt-pM2MYqeOR6ITsKgnv04E1WlNw1iY"
